import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@progress/kendo-theme-default/dist/all.css";
import { MenuContextProvider } from "../../context/MenuContext";
import StyledComponentsRegistry from "../../lib/registry";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <MenuContextProvider>
      <html lang="en">
        <StyledComponentsRegistry>
          <body className={roboto.className}>{children}</body>
        </StyledComponentsRegistry>
      </html>
    </MenuContextProvider>
  );
}
